//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package grs;

public class AthletUI extends de.tum.ascodt.plugin.ui.tabs.UITab {
     
     public AthletUI(Athlet component){
          super(component);
     }
     /**
      * here you need to instantiate your own controls
      * use _tabFolderPage as parent
      */
     @Override
     protected void createControlGroup() {
          // TODO Auto-generated method stub
          
     }
     
     private Athlet getCastedComponent(){
          if(_component instanceof Athlet){
               return (Athlet) _component;
          }
          return null;
     }
}
