//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package grs;


public class AthletBasisJavaImplementation extends grs.AthletAbstractJavaImplementation {
  public AthletBasisJavaImplementation( String identifier ) {
    super(identifier);
  }
  
  /**
   * Provides methods block
   */

}
 

