!
! ASCoDT - Advanced Scientific Computing Development Toolkit
!
! This file was generated by ASCoDT's simplified SIDL compiler.
!
! Authors: Tobias Weinzierl, Atanas Atanasov   
!
module grs_QuaboxImplementation
use grs_quaboxAbstractImplementation
implicit none

type, extends ( QuaboxAbstractImplementation ), public :: QuaboxImplementation 
     ! Declaration of private members
     private 
     !list of procedures
     contains
     procedure,public::createInstance
     procedure,public::destroyInstance
     procedure,public::n3inp_transferCAI
procedure,public::n3inp_transferCADIMN
procedure,public::n3inp_transferCANW
procedure,public::n3inp_transferCCC
procedure,public::n3inp_transferCDGE
procedure,public::n3inp_transferCDNW
procedure,public::n3inp_transferCHCD
procedure,public::n3inp_transferCHCP
procedure,public::n3inp_transferCRCI
procedure,public::n3inp_invoke
procedure,public::n3inte_transferCCA
procedure,public::n3inte_transferCCAC
procedure,public::n3inte_transferCCC
procedure,public::n3inte_transferCGCO
procedure,public::n3inte_transferCHCD
procedure,public::n3inte_transferCHCO
procedure,public::n3inte_transferCHCP
procedure,public::n3inte_transferCNI
procedure,public::n3inte_transferCNK
procedure,public::n3inte_transferCNR
procedure,public::n3inte_invoke
procedure,public::n3inte_transferResults
procedure,public::n3set_transferCCC
procedure,public::n3set_transferCDGE
procedure,public::n3set_transferCDML
procedure,public::n3set_transferCDNW
procedure,public::n3set_transferCDPR
procedure,public::n3set_transferCDQ
procedure,public::n3set_transferCDSS
procedure,public::n3set_transferCDTF
procedure,public::n3set_transferCGCO
procedure,public::n3set_transferCHCD
procedure,public::n3set_transferCHCP
procedure,public::n3set_transferCHCO
procedure,public::n3set_transferCHRD
procedure,public::n3set_transferCKBO
procedure,public::n3set_transferCNI
procedure,public::n3set_invoke
procedure,public::n3set_transferResults
procedure,public::n3rest_transferCCA
procedure,public::n3rest_transferCNK
procedure,public::n3rest_transferCNR
procedure,public::n3rest_transferCNI
procedure,public::n3rest_invoke
procedure,public::n3rest_transferResults
procedure,public::setup
procedure,public::start

end type QuaboxImplementation
type(QuaboxImplementation ),allocatable::Quabox_instance
contains 

subroutine createInstance(this)
    class( QuaboxImplementation)::this
    !put your initialization code here
end subroutine createInstance

subroutine destroyInstance(this)
     class( QuaboxImplementation)::this
     !put your destructor code here
end subroutine destroyInstance

subroutine start(this)
    class( QuaboxImplementation)::this
    
    !put your implementation here
end subroutine start
subroutine setup(this)
    use, intrinsic :: iso_c_binding
    class( QuaboxImplementation)::this
    !if(this%is_valid()) then
        call this%logger%info("grs.Quabox", "start setup Quabox")
       !call athlet_setup()
       CALL APRESET
      CALL EPRESET
      CALL FPRESET

      CALL AGETPA


      CALL ERRSET( 208, 0, 20,2,0,208)
      CALL ERRSET( 202,10,255,2,0,202)
      CALL ERRSET( 141,10,255,2,0,141)
      CALL ERRSET( 162, 0, 20,2,0,162)
      CALL ERRSET( 163, 0, 20,2,0,163)
      CALL ERRSET( 187,10,255,2,0,187)
      CALL ERRSET( 209,10,255,2,0,209)
      !KEYA1  = 100

      CALL AIN0
      CALL ADIM
      !KEYA1  = 200
      CALL AIN1
      CLOSE (UNIT=1)

        call this%logger%info("grs.Quabox", "finish setup Quabox")
    !endif
    !put your implementation here
end subroutine setup
subroutine n3rest_transferResults(this,&
	QNKI0I,QNKI0I_len)
    class( QuaboxImplementation)::this
    	real(8),intent(inout),dimension(*)::QNKI0I
	integer,intent(in)::QNKI0I_len

    !put your implementation here
end subroutine n3rest_transferResults
subroutine n3rest_invoke(this,&
	IDIR,&
	IFORM,&
	IUN)
    class( QuaboxImplementation)::this
    	integer,intent(in)::IDIR
	integer,intent(in)::IFORM
	integer,intent(in)::IUN

    !put your implementation here
end subroutine n3rest_invoke
subroutine n3rest_transferCNI(this,&
	NKSGMX)
    class( QuaboxImplementation)::this
    	integer,intent(in)::NKSGMX

    !put your implementation here
end subroutine n3rest_transferCNI
subroutine n3rest_transferCNR(this,&
	QNKI0I,QNKI0I_len)
    class( QuaboxImplementation)::this
    	real(8),intent(in),dimension(*)::QNKI0I
	integer,intent(in)::QNKI0I_len

    !put your implementation here
end subroutine n3rest_transferCNR
subroutine n3rest_transferCNK(this,&
	INITIA,&
	QD,QD_len)
    class( QuaboxImplementation)::this
    	integer,intent(in)::INITIA
	real(8),intent(in),dimension(*)::QD
	integer,intent(in)::QD_len

    !put your implementation here
end subroutine n3rest_transferCNK
subroutine n3rest_transferCCA(this,&
	L3DNK)
    class( QuaboxImplementation)::this
    	integer,intent(in)::L3DNK

    !put your implementation here
end subroutine n3rest_transferCCA
subroutine n3set_transferResults(this,&
	XBOR,XBOR_len,&
	NLAYSK,NLAYSK_len,&
	INLAYS,&
	ISDK)
    class( QuaboxImplementation)::this
    	real(8),intent(inout),dimension(*)::XBOR
	integer,intent(in)::XBOR_len
	integer,intent(inout),dimension(*)::NLAYSK
	integer,intent(in)::NLAYSK_len
	integer,intent(inout)::INLAYS
	integer,intent(inout)::ISDK

    !put your implementation here
end subroutine n3set_transferResults
subroutine n3set_invoke(this,&
	NSEGS,NSEGS_len,&
	IZONE,IZONE_len,&
	NOLAYS,NOLAYS_len,&
	SV,SV_len,&
	TT,TT_len,&
	IQF,IQF_len,&
	ISEG,ISEG_len,&
	ISD)
    class( QuaboxImplementation)::this
    	integer,intent(in),dimension(*)::NSEGS
	integer,intent(in)::NSEGS_len
	integer,intent(in),dimension(*)::IZONE
	integer,intent(in)::IZONE_len
	integer,intent(in),dimension(*)::NOLAYS
	integer,intent(in)::NOLAYS_len
	real(8),intent(in),dimension(*)::SV
	integer,intent(in)::SV_len
	real(8),intent(in),dimension(*)::TT
	integer,intent(in)::TT_len
	integer,intent(in),dimension(*)::IQF
	integer,intent(in)::IQF_len
	integer,intent(in),dimension(*)::ISEG
	integer,intent(in)::ISEG_len
	integer,intent(in)::ISD

    !put your implementation here
end subroutine n3set_invoke
subroutine n3set_transferCNI(this,&
	NLAYSK,NLAYSK_len,&
	INLAYS,&
	ISDK)
    class( QuaboxImplementation)::this
    	integer,intent(in),dimension(*)::NLAYSK
	integer,intent(in)::NLAYSK_len
	integer,intent(in)::INLAYS
	integer,intent(in)::ISDK

    !put your implementation here
end subroutine n3set_transferCNI
subroutine n3set_transferCKBO(this,&
	LBORON,&
	CBOR,CBOR_len,&
	XBOR,XBOR_len)
    class( QuaboxImplementation)::this
    	logical,intent(in)::LBORON
	real(8),intent(in),dimension(*)::CBOR
	integer,intent(in)::CBOR_len
	real(8),intent(in),dimension(*)::XBOR
	integer,intent(in)::XBOR_len

    !put your implementation here
end subroutine n3set_transferCKBO
subroutine n3set_transferCHRD(this,&
	LFLUID,LFLUID_len)
    class( QuaboxImplementation)::this
    	integer,intent(in),dimension(*)::LFLUID
	integer,intent(in)::LFLUID_len

    !put your implementation here
end subroutine n3set_transferCHRD
subroutine n3set_transferCHCO(this,&
	HC,HC_len)
    class( QuaboxImplementation)::this
    	real(8),intent(in),dimension(*)::HC
	integer,intent(in)::HC_len

    !put your implementation here
end subroutine n3set_transferCHCO
subroutine n3set_transferCHCP(this,&
	POWERN,POWERN_len)
    class( QuaboxImplementation)::this
    	real(8),intent(in),dimension(*)::POWERN
	integer,intent(in)::POWERN_len

    !put your implementation here
end subroutine n3set_transferCHCP
subroutine n3set_transferCHCD(this,&
	NKHCO,NKHCO_len)
    class( QuaboxImplementation)::this
    	integer,intent(in),dimension(*)::NKHCO
	integer,intent(in)::NKHCO_len

    !put your implementation here
end subroutine n3set_transferCHCD
subroutine n3set_transferCGCO(this,&
	LSGIMP,&
	YNAME,YNAME_len)
    class( QuaboxImplementation)::this
    	integer,intent(in)::LSGIMP
	character(*),intent(in),dimension(*)::YNAME
	integer,intent(in)::YNAME_len

    !put your implementation here
end subroutine n3set_transferCGCO
subroutine n3set_transferCDTF(this,&
	XQM,XQM_len,&
	AV,AV_len,&
	ROF,ROF_len,&
	IKS)
    class( QuaboxImplementation)::this
    	real(8),intent(in),dimension(*)::XQM
	integer,intent(in)::XQM_len
	real(8),intent(in),dimension(*)::AV
	integer,intent(in)::AV_len
	real(8),intent(in),dimension(*)::ROF
	integer,intent(in)::ROF_len
	integer,intent(in)::IKS

    !put your implementation here
end subroutine n3set_transferCDTF
subroutine n3set_transferCDSS(this,&
	NSSITE)
    class( QuaboxImplementation)::this
    	integer,intent(in)::NSSITE

    !put your implementation here
end subroutine n3set_transferCDSS
subroutine n3set_transferCDQ(this,&
	QI,QI_len)
    class( QuaboxImplementation)::this
    	real(8),intent(in),dimension(*)::QI
	integer,intent(in)::QI_len

    !put your implementation here
end subroutine n3set_transferCDQ
subroutine n3set_transferCDPR(this,&
	TFHT,TFHT_len,&
	TL,TL_len)
    class( QuaboxImplementation)::this
    	real(8),intent(in),dimension(*)::TFHT
	integer,intent(in)::TFHT_len
	real(8),intent(in),dimension(*)::TL
	integer,intent(in)::TL_len

    !put your implementation here
end subroutine n3set_transferCDPR
subroutine n3set_transferCDNW(this,&
	IILO,IILO_len,&
	IIRO,IIRO_len)
    class( QuaboxImplementation)::this
    	integer,intent(in),dimension(*)::IILO
	integer,intent(in)::IILO_len
	integer,intent(in),dimension(*)::IIRO
	integer,intent(in)::IIRO_len

    !put your implementation here
end subroutine n3set_transferCDNW
subroutine n3set_transferCDML(this,&
	IMLK,IMLK_len,&
	IML,IML_len)
    class( QuaboxImplementation)::this
    	integer,intent(in),dimension(*)::IMLK
	integer,intent(in)::IMLK_len
	integer,intent(in),dimension(*)::IML
	integer,intent(in)::IML_len

    !put your implementation here
end subroutine n3set_transferCDML
subroutine n3set_transferCDGE(this,&
	VOLI,VOLI_len,&
	ZTI,ZTI_len,&
	ZBI,ZBI_len)
    class( QuaboxImplementation)::this
    	real(8),intent(in),dimension(*)::VOLI
	integer,intent(in)::VOLI_len
	real(8),intent(in),dimension(*)::ZTI
	integer,intent(in)::ZTI_len
	real(8),intent(in),dimension(*)::ZBI
	integer,intent(in)::ZBI_len

    !put your implementation here
end subroutine n3set_transferCDGE
subroutine n3set_transferCCC(this,&
	KEYA1)
    class( QuaboxImplementation)::this
    	integer,intent(in)::KEYA1

    !put your implementation here
end subroutine n3set_transferCCC
subroutine n3inte_transferResults(this,&
	POWERN,POWERN_len,&
	QNKI0,QNKI0_len,&
	INITIA)
    class( QuaboxImplementation)::this
    	real(8),intent(inout),dimension(*)::POWERN
	integer,intent(in)::POWERN_len
	real(8),intent(inout),dimension(*)::QNKI0
	integer,intent(in)::QNKI0_len
	integer,intent(inout)::INITIA

    !put your implementation here
end subroutine n3inte_transferResults
subroutine n3inte_invoke(this,&
	ITERNB,&
	LINIK,&
	QNKI,QNKI_len)
    class( QuaboxImplementation)::this
    	integer,intent(inout)::ITERNB
	logical,intent(in)::LINIK
	real(8),intent(inout),dimension(*)::QNKI
	integer,intent(in)::QNKI_len

    !put your implementation here
end subroutine n3inte_invoke
subroutine n3inte_transferCNR(this,&
	QNKI0,QNKI0_len)
    class( QuaboxImplementation)::this
    	real(8),intent(in),dimension(*)::QNKI0
	integer,intent(in)::QNKI0_len

    !put your implementation here
end subroutine n3inte_transferCNR
subroutine n3inte_transferCNK(this,&
	INITIA)
    class( QuaboxImplementation)::this
    	integer,intent(in)::INITIA

    !put your implementation here
end subroutine n3inte_transferCNK
subroutine n3inte_transferCNI(this,&
	NKSGMX,&
	NNRODK)
    class( QuaboxImplementation)::this
    	integer,intent(in)::NKSGMX
	integer,intent(in)::NNRODK

    !put your implementation here
end subroutine n3inte_transferCNI
subroutine n3inte_transferCHCP(this,&
	IAHO,IAHO_len,&
	LHCU,&
	LHLENG,&
	POWERN,POWERN_len)
    class( QuaboxImplementation)::this
    	integer,intent(in),dimension(*)::IAHO
	integer,intent(in)::IAHO_len
	integer,intent(in)::LHCU
	integer,intent(in)::LHLENG
	real(8),intent(inout),dimension(*)::POWERN
	integer,intent(in)::POWERN_len

    !put your implementation here
end subroutine n3inte_transferCHCP
subroutine n3inte_transferCHCO(this,&
	HC,HC_len)
    class( QuaboxImplementation)::this
    	real(8),intent(in),dimension(*)::HC
	integer,intent(in)::HC_len

    !put your implementation here
end subroutine n3inte_transferCHCO
subroutine n3inte_transferCHCD(this,&
	NKHCO,NKHCO_len)
    class( QuaboxImplementation)::this
    	integer,intent(in),dimension(*)::NKHCO
	integer,intent(in)::NKHCO_len

    !put your implementation here
end subroutine n3inte_transferCHCD
subroutine n3inte_transferCGCO(this,&
	TE)
    class( QuaboxImplementation)::this
    	real(8),intent(in)::TE

    !put your implementation here
end subroutine n3inte_transferCGCO
subroutine n3inte_transferCCC(this,&
	KEYA1,&
	KEYE,&
	KEYOUT)
    class( QuaboxImplementation)::this
    	integer,intent(in)::KEYA1
	integer,intent(in)::KEYE
	integer,intent(in)::KEYOUT

    !put your implementation here
end subroutine n3inte_transferCCC
subroutine n3inte_transferCCAC(this,&
	TFFKT,&
	TFFKT0)
    class( QuaboxImplementation)::this
    	real(8),intent(in)::TFFKT
	real(8),intent(in)::TFFKT0

    !put your implementation here
end subroutine n3inte_transferCCAC
subroutine n3inte_transferCCA(this,&
	L3DNK,&
	DT,&
	T)
    class( QuaboxImplementation)::this
    	integer,intent(in)::L3DNK
	real(8),intent(in)::DT
	real(8),intent(in)::T

    !put your implementation here
end subroutine n3inte_transferCCA
subroutine n3inp_invoke(this)
    class( QuaboxImplementation)::this
    
    !put your implementation here
end subroutine n3inp_invoke
subroutine n3inp_transferCRCI(this,&
	IQF10,IQF10_len,&
	AROD,AROD_len)
    class( QuaboxImplementation)::this
    	integer,intent(in),dimension(*)::IQF10
	integer,intent(in)::IQF10_len
	character(*),intent(in),dimension(*)::AROD
	integer,intent(in)::AROD_len

    !put your implementation here
end subroutine n3inp_transferCRCI
subroutine n3inp_transferCHCP(this,&
	NRODS,&
	IHVMAX)
    class( QuaboxImplementation)::this
    	integer,intent(in)::NRODS
	integer,intent(in)::IHVMAX

    !put your implementation here
end subroutine n3inp_transferCHCP
subroutine n3inp_transferCHCD(this,&
	NHOBJ,&
	ACOMP0,ACOMP0_len,&
	ANAMH,ANAMH_len,&
	AOLH,AOLH_len,&
	AORH,AORH_len,&
	FPROD,FPROD_len)
    class( QuaboxImplementation)::this
    	integer,intent(in)::NHOBJ
	character(*),intent(in),dimension(*)::ACOMP0
	integer,intent(in)::ACOMP0_len
	character(*),intent(in),dimension(*)::ANAMH
	integer,intent(in)::ANAMH_len
	character(*),intent(in),dimension(*)::AOLH
	integer,intent(in)::AOLH_len
	character(*),intent(in),dimension(*)::AORH
	integer,intent(in)::AORH_len
	real(8),intent(in),dimension(*)::FPROD
	integer,intent(in)::FPROD_len

    !put your implementation here
end subroutine n3inp_transferCHCD
subroutine n3inp_transferCDNW(this,&
	IILO,IILO_len,&
	IIRO,IIRO_len)
    class( QuaboxImplementation)::this
    	integer,intent(in),dimension(*)::IILO
	integer,intent(in)::IILO_len
	integer,intent(in),dimension(*)::IIRO
	integer,intent(in)::IIRO_len

    !put your implementation here
end subroutine n3inp_transferCDNW
subroutine n3inp_transferCDGE(this,&
	ZBI,ZBI_len)
    class( QuaboxImplementation)::this
    	real(8),intent(in),dimension(*)::ZBI
	integer,intent(in)::ZBI_len

    !put your implementation here
end subroutine n3inp_transferCDGE
subroutine n3inp_transferCCC(this,&
	CARD,&
	IOIN,&
	IOPRI)
    class( QuaboxImplementation)::this
    	character(*),intent(in)::CARD
	integer,intent(in)::IOIN
	integer,intent(in)::IOPRI

    !put your implementation here
end subroutine n3inp_transferCCC
subroutine n3inp_transferCANW(this,&
	NOBJ,&
	ANAMO,ANAMO_len)
    class( QuaboxImplementation)::this
    	integer,intent(in)::NOBJ
	character(*),intent(in),dimension(*)::ANAMO
	integer,intent(in)::ANAMO_len

    !put your implementation here
end subroutine n3inp_transferCANW
subroutine n3inp_transferCADIMN(this,&
	INM03)
    class( QuaboxImplementation)::this
    	integer,intent(in)::INM03

    !put your implementation here
end subroutine n3inp_transferCADIMN
subroutine n3inp_transferCAI(this,&
	AIKEY_in,AIKEY_len,&
	AICONT_in,AICONT_len)
	use CAI, only: AIKEY,AICONT
    class( QuaboxImplementation)::this
     character(*),intent(in),dimension(*)::AIKEY_in
    character(*),intent(in),dimension(*)::AICONT_in
    integer,intent(in)::AIKEY_len
    integer,intent(in)::AICONT_len
    integer::i
    !!print *,"n3inp_transferCAI out"
    if(.not.allocated(AIKEY)) then
         allocate(AIKEY(AIKEY_len))
    end if

    do i = 1, AIKEY_len
        AIKEY(i)=AIKEY_in(i)
    end do
     if(.not.allocated(AICONT)) then
       allocate(AICONT(AICONT_len))

    end if
      do i = 1, AICONT_len
        AICONT(i)=AICONT_in(i)
        !!print *,"Cont_word:",AICONT(i)
    end do

    !put your implementation here
end subroutine n3inp_transferCAI


end module  grs_QuaboxImplementation



PROGRAM Quabox
    call socket_server_loop()

end PROGRAM
