//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package grs;


public class QuaboxBasisJavaImplementation extends grs.QuaboxAbstractJavaImplementation {
  public QuaboxBasisJavaImplementation( String identifier ) {
    super(identifier);
  }
  
  /**
   * Provides methods block
   */

}
 

