//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package de.tum;


public class MyTestComponentBasisJavaImplementation extends de.tum.MyTestComponentAbstractJavaImplementation {
  public MyTestComponentBasisJavaImplementation( String identifier ) {
    super(identifier);
  }
  
  /**
   * Provides methods block
   */

}
 

