//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package de.tum.charts;


public class LinePlotterBasisJavaImplementation extends de.tum.charts.LinePlotterAbstractJavaImplementation {
  public LinePlotterBasisJavaImplementation( String identifier ) {
    super(identifier);
  }
  
  /**
   * Provides methods block
   */

}
 

