//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package de.tum.charts;

public class LinePlotterUI extends de.tum.ascodt.plugin.ui.tabs.UITab {
     
     public LinePlotterUI(LinePlotter component){
          super(component);
     }
     /**
      * here you need to instantiate your own controls
      * use _tabFolderPage as parent
      */
     @Override
     protected void createControlGroup() {
          // TODO Auto-generated method stub
          
     }
     
     private LinePlotter getCastedComponent(){
          if(_component instanceof LinePlotter){
               return (LinePlotter) _component;
          }
          return null;
     }
}
