//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package de.tum.charts;


public class LinePlotterJavaImplementation extends LinePlotterBasisJavaImplementation {
  
  private LinePlotterUI _ui;

public LinePlotterJavaImplementation( String identifier ) {
    super(identifier);
    _ui = new LinePlotterUI(this);
    _ui.setVisible(false);
  }
  
  
  public boolean isValid() {
    // @todo Insert your code here
    return true;
  }


  public boolean hasGUI() {
    return true;
  }
  
  
  public void openGUI() {
	  _ui.setVisible(true);
  }
  
  
  public void closeGUI() {
	  _ui.setVisible(false);
  }

  public void destroy(){
     super.destroy();
  }

}
 


