/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tum.ascodt.sidlcompiler.frontend.node;

import java.util.*;
import de.tum.ascodt.sidlcompiler.frontend.analysis.*;

@SuppressWarnings("nls")
public final class ADeclaration extends PDeclaration
{
    private final LinkedList<PPackage> _package_ = new LinkedList<PPackage>();

    public ADeclaration()
    {
        // Constructor
    }

    public ADeclaration(
        @SuppressWarnings("hiding") List<PPackage> _package_)
    {
        // Constructor
        setPackage(_package_);

    }

    @Override
    public Object clone()
    {
        return new ADeclaration(
            cloneList(this._package_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclaration(this);
    }

    public LinkedList<PPackage> getPackage()
    {
        return this._package_;
    }

    public void setPackage(List<PPackage> list)
    {
        this._package_.clear();
        this._package_.addAll(list);
        for(PPackage e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._package_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._package_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PPackage> i = this._package_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PPackage) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
