/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tum.ascodt.sidlcompiler.frontend.node;

import java.util.*;
import de.tum.ascodt.sidlcompiler.frontend.analysis.*;

@SuppressWarnings("nls")
public final class AEnumDeclarationPackageElement extends PPackageElement
{
    private TIdentifier _name_;
    private final LinkedList<PEnumerator> _enumerator_ = new LinkedList<PEnumerator>();

    public AEnumDeclarationPackageElement()
    {
        // Constructor
    }

    public AEnumDeclarationPackageElement(
        @SuppressWarnings("hiding") TIdentifier _name_,
        @SuppressWarnings("hiding") List<PEnumerator> _enumerator_)
    {
        // Constructor
        setName(_name_);

        setEnumerator(_enumerator_);

    }

    @Override
    public Object clone()
    {
        return new AEnumDeclarationPackageElement(
            cloneNode(this._name_),
            cloneList(this._enumerator_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEnumDeclarationPackageElement(this);
    }

    public TIdentifier getName()
    {
        return this._name_;
    }

    public void setName(TIdentifier node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    public LinkedList<PEnumerator> getEnumerator()
    {
        return this._enumerator_;
    }

    public void setEnumerator(List<PEnumerator> list)
    {
        this._enumerator_.clear();
        this._enumerator_.addAll(list);
        for(PEnumerator e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._name_)
            + toString(this._enumerator_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        if(this._enumerator_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._name_ == oldChild)
        {
            setName((TIdentifier) newChild);
            return;
        }

        for(ListIterator<PEnumerator> i = this._enumerator_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PEnumerator) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
