/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tum.ascodt.sidlcompiler.frontend.node;

import de.tum.ascodt.sidlcompiler.frontend.analysis.*;

@SuppressWarnings("nls")
public final class ASubpackagePackageElement extends PPackageElement
{
    private PPackage _package_;

    public ASubpackagePackageElement()
    {
        // Constructor
    }

    public ASubpackagePackageElement(
        @SuppressWarnings("hiding") PPackage _package_)
    {
        // Constructor
        setPackage(_package_);

    }

    @Override
    public Object clone()
    {
        return new ASubpackagePackageElement(
            cloneNode(this._package_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASubpackagePackageElement(this);
    }

    public PPackage getPackage()
    {
        return this._package_;
    }

    public void setPackage(PPackage node)
    {
        if(this._package_ != null)
        {
            this._package_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._package_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._package_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._package_ == child)
        {
            this._package_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._package_ == oldChild)
        {
            setPackage((PPackage) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
