/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tum.ascodt.sidlcompiler.frontend.node;

import java.util.*;
import de.tum.ascodt.sidlcompiler.frontend.analysis.*;

@SuppressWarnings("nls")
public final class AUserDefinedType extends PUserDefinedType
{
    private final LinkedList<TIdentifier> _identifier_ = new LinkedList<TIdentifier>();

    public AUserDefinedType()
    {
        // Constructor
    }

    public AUserDefinedType(
        @SuppressWarnings("hiding") List<TIdentifier> _identifier_)
    {
        // Constructor
        setIdentifier(_identifier_);

    }

    @Override
    public Object clone()
    {
        return new AUserDefinedType(
            cloneList(this._identifier_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUserDefinedType(this);
    }

    public LinkedList<TIdentifier> getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(List<TIdentifier> list)
    {
        this._identifier_.clear();
        this._identifier_.addAll(list);
        for(TIdentifier e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identifier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identifier_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<TIdentifier> i = this._identifier_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((TIdentifier) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
