/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tum.ascodt.sidlcompiler.frontend.node;

import java.util.*;
import de.tum.ascodt.sidlcompiler.frontend.analysis.*;

@SuppressWarnings("nls")
public final class AUses extends PUses
{
    private final LinkedList<PUserDefinedType> _type_ = new LinkedList<PUserDefinedType>();
    private TIdentifier _as_;

    public AUses()
    {
        // Constructor
    }

    public AUses(
        @SuppressWarnings("hiding") List<PUserDefinedType> _type_,
        @SuppressWarnings("hiding") TIdentifier _as_)
    {
        // Constructor
        setType(_type_);

        setAs(_as_);

    }

    @Override
    public Object clone()
    {
        return new AUses(
            cloneList(this._type_),
            cloneNode(this._as_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUses(this);
    }

    public LinkedList<PUserDefinedType> getType()
    {
        return this._type_;
    }

    public void setType(List<PUserDefinedType> list)
    {
        this._type_.clear();
        this._type_.addAll(list);
        for(PUserDefinedType e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    public TIdentifier getAs()
    {
        return this._as_;
    }

    public void setAs(TIdentifier node)
    {
        if(this._as_ != null)
        {
            this._as_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._as_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._type_)
            + toString(this._as_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._type_.remove(child))
        {
            return;
        }

        if(this._as_ == child)
        {
            this._as_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PUserDefinedType> i = this._type_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PUserDefinedType) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._as_ == oldChild)
        {
            setAs((TIdentifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
