/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tum.ascodt.sidlcompiler.frontend.node;

import de.tum.ascodt.sidlcompiler.frontend.analysis.*;

@SuppressWarnings("nls")
public final class TAsToken extends Token
{
    public TAsToken()
    {
        super.setText("as");
    }

    public TAsToken(int line, int pos)
    {
        super.setText("as");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAsToken(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAsToken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAsToken text.");
    }
}
