/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tum.ascodt.sidlcompiler.frontend.node;

import de.tum.ascodt.sidlcompiler.frontend.analysis.*;

@SuppressWarnings("nls")
public final class TInterfaceToken extends Token
{
    public TInterfaceToken()
    {
        super.setText("interface");
    }

    public TInterfaceToken(int line, int pos)
    {
        super.setText("interface");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TInterfaceToken(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTInterfaceToken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TInterfaceToken text.");
    }
}
