/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tum.ascodt.sidlcompiler.frontend.node;

import de.tum.ascodt.sidlcompiler.frontend.analysis.*;

@SuppressWarnings("nls")
public final class TInToken extends Token
{
    public TInToken()
    {
        super.setText("in");
    }

    public TInToken(int line, int pos)
    {
        super.setText("in");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TInToken(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTInToken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TInToken text.");
    }
}
