/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tum.ascodt.sidlcompiler.frontend.node;

import de.tum.ascodt.sidlcompiler.frontend.analysis.*;

@SuppressWarnings("nls")
public final class TTargetToken extends Token
{
    public TTargetToken()
    {
        super.setText("@target");
    }

    public TTargetToken(int line, int pos)
    {
        super.setText("@target");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTargetToken(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTargetToken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTargetToken text.");
    }
}
