/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tum.ascodt.sidlcompiler.frontend.node;

import de.tum.ascodt.sidlcompiler.frontend.analysis.*;

@SuppressWarnings("nls")
public final class TUsesToken extends Token
{
    public TUsesToken()
    {
        super.setText("uses");
    }

    public TUsesToken(int line, int pos)
    {
        super.setText("uses");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TUsesToken(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTUsesToken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TUsesToken text.");
    }
}
